# Generated by Django 3.1.5 on 2021-01-21 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20210121_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='NewImage',
        ),
    ]
